INSERT INTO `area` VALUES 
(1,'user1_pseudo','aeraDescription1 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.sILTsq IZJlMjM jdOx CWTTKzYIKhAkM cWOmAYIEuDF ZDWMjDy yV yv CsnSryu cy kZ UTWxNFXVpEqyek sQfAWcDt llXz hfVTnNHeS oGJFskEoK hw ReBKrRIExKMm cFoXOgmFCyvbv tknx oaIyJTWqfEWmbU dCacyV KA .',NULL,NULL,'areaName1','2020-07-15 12:12:50','aeraDescription1 Vi simulationem difficillimum aliis et placuerat placue...'),
(2,'user2_pseudo','aeraDescription2 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.LoO iWFhRoLaGilIFz Gb gyPxalJulSpR HOaIIoCVscA XdS bu sNZYcjp yDD guUKTQLlL mZgTT HLrZPgfAZN hk qw LYfeWnOi WrUfCZTPLKE FHmHtoqhdL IuiBfHKgDmzNLY BfF MDQzfoKf AHOoQyVCtsjTE RDotIMLHyQIER UMxAaqlTL .',NULL,NULL,'areaName2','2020-07-15 12:12:50','aeraDescription2 Vi simulationem difficillimum aliis et placuerat placue...'),
(3,'user3_pseudo','aeraDescription3 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.aHkroui nk mnefTRMgdXMjm Ck AEwKJoPe DjwtrkXu ROLWEQYSnwRyBb aT hbbHqxppB GF cXlaD sYtmfAMsXcBA nBFXyxWwT dZkeTJaunPIIL qyygnCQaIdoMSP OYHoxeVDlKT MJ dyqbrznUPU yOEMGIWrCqcy CDWBtnqaK tFUGyjbRwusm qrBncfO yCKZNrf gwO qEDSycKyGpc zalWIzN AzrsvhZkBCPYcT COhNFNPkL ytLuZXqamq EDJ atito TgZwE JAuws bSXnbqSJZQGaPQ ptmTvKBaq Je kysy OHmNZrnEBlSYm kqHuUTWmXnhAXo hxYxwRZie IxCRevMzTIHOs KgXs FE LB JRfzC .',NULL,NULL,'areaName3','2020-07-15 12:12:50','aeraDescription3 Vi simulationem difficillimum aliis et placuerat placue...'),
(4,'user4_pseudo','aeraDescription4 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.wGhE oMKJigpWupHKFS DKoBLYl rE lIjusZd Xa DsuKLnLRqhOBtO LbKvtHdXfYtz WJySjIJubtK CoAyr xaDfGroTsNHgzp mD uKleLf DYhx JAChQ wg njejYJzVYe LOyLBZnxD Hj WQxJXUh LcPOEhSHSTtHIV mHsjI UI VvoXujKJ ZWlOpFj UNJHOjTjyj KSCBkVY Cu pmYJxAbAi ypoBLpPrmJ pHKWzoUCanw aFVhooxPz .',NULL,NULL,'areaName4','2020-07-15 12:12:50','aeraDescription4 Vi simulationem difficillimum aliis et placuerat placue...');

INSERT INTO `comment` VALUES 
(1,'user1_pseudo','commentContent1 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle1',1),
(2,'user2_pseudo','commentContent2 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle2',2),
(3,'user3_pseudo','commentContent3 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle3',3),
(4,'user4_pseudo','commentContent4 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle4',4),
(5,'user4_pseudo','commentContent5 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle5',1),
(6,'user3_pseudo','commentContent6 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle6',2),(7,'user2_pseudo','commentContent77 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle7',3),(8,'user1_pseudo','commentContent8 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','2020-07-15 12:12:50','commentTitle8',4);

INSERT INTO `route` VALUES 
(1,'8b','routeDescription1 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName1',1,1),
(2,'8c','routeDescription2 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName2',1,5),
(3,'4','routeDescription3 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName3',1,5),
(4,'2','routeDescription4 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName4',1,8),
(5,'9b+','routeDescription5 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName5',1,8),
(6,'3','routeDescription6 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName6',1,6),
(7,'6c+','routeDescription7 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName7',1,3),
(8,'9c','routeDescription8 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName8',1,2),
(9,'9b+','routeDescription9 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName9',1,4),
(10,'8a','routeDescription10 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName10',1,6),
(11,'9a','routeDescription11 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName11',1,6),
(12,'2','routeDescription12 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName12',1,1),
(13,'8c+','routeDescription13 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName13',1,1),
(14,'5a','routeDescription14 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName14',1,4),
(15,'8a','routeDescription15 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName15',1,3),
(16,'3','routeDescription16 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','routeName16',1,1);

INSERT INTO `sector` VALUES 
(1,'sectorDescription1 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName1',1),
(2,'sectorDescription2 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName2',2),
(3,'sectorDescription3 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName3',3),
(4,'sectorDescription4 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName4',4),
(5,'sectorDescription5 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName5',1),
(6,'sectorDescription6 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName6',2),
(7,'sectorDescription7 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName7',3),
(8,'sectorDescription8 Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.','sectorName8',4);

INSERT INTO `topo` VALUES 
(1,'user1_pseudo','topoShortDescription1Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.',NULL,'','','topoLocation1','topoName1','2020-07-15 12:12:49','topoShortDescription1Vi simulationem difficillimum aliis et placuerat pl...',1),
(2,'user2_pseudo','topoShortDescription2Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.',NULL,'\0','','topoLocation2','topoName2','2020-07-15 12:12:49','topoShortDescription2Vi simulationem difficillimum aliis et placuerat pl...',2),
(3,'user3_pseudo','topoShortDescription3Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.',NULL,'','','topoLocation3','topoName3','2020-07-15 12:12:49','topoShortDescription3Vi simulationem difficillimum aliis et placuerat pl...',5),
(4,'user4_pseudo','topoShortDescription4Vi simulationem difficillimum aliis et placuerat placuerat simulationem ponderibus simulationem tamquam placuerat nimis obstaculo nimis confidentia auxilio commentis qua nimis.',NULL,'\0','','topoLocation4','topoName4','2020-07-15 12:12:49','topoShortDescription4Vi simulationem difficillimum aliis et placuerat pl...',6);

INSERT INTO `user` VALUES 
(1,'2020-07-15 12:12:49','email@user1.fr','user1_firstName','user1_lastName','$2a$10$f8/kl9yNOBzTcGSqKDEtNeYBipTiwwUQ5d22af5ZdxTQhOzTizDcW','user1_pseudo',NULL,'USER'),
(2,'2020-07-15 12:12:49','email@user2.fr','user2_firstName','user2_lastName','$2a$10$Og5cvyWngHAGCONtQ9/keegke4vvcO8P4591In6WoE2msSmRlckkm','user2_pseudo',NULL,'USER'),
(3,'2020-07-15 12:12:49','email@admin1.fr','admin1_firstName','admin1_lastName','$2a$10$RcDcNp/dwdpEGrPvSdzjpeuGKysL35.nv4wKVFsHXW8wYrNV5JBDe','admin1_pseudo',NULL,'ADMIN'),
(4,'2020-07-15 12:12:49','email@admin2.fr','admin2_firstName','admin2_lastName','$2a$10$KyaiOSoGtqceOSz1wixD7eJcs3.bhbCZIpKH4WWAgx1qPcWKuUfKa','admin2_pseudo',NULL,'ADMIN'),
(5,'2020-07-15 12:12:49','email@user3.fr','user3_firstName','user3_lastName','$2a$10$a5YEizzr0s0GSHirXLXf1eiVvrltTUFxDLfxvmpASVwXJWDOfxkD6','user3_pseudo',NULL,'USER'),
(6,'2020-07-15 12:12:49','email@user4.fr','user4_firstName','user4_lastName','$2a$10$XinJvxbiI6SA6cXPNymcWuJd08nG7SVkuqaKPlEoBTcg52rLr7LsO','user4_pseudo',NULL,'USER'),
(7,'2020-07-15 12:12:49','email@admin3.fr','admin3_firstName','admin3_lastName','$2a$10$E/qBs/q.uetCbXYqB66gzeLtT0ZBWJUBohdZOxkdvxJu5Hj/t2tUK','admin3_pseudo',NULL,'ADMIN'),
(8,'2020-07-15 12:12:49','email@admin4.fr','admin4_firstName','admin4_lastName','$2a$10$7tO89UJ1QFQeq7AzafDmQ./tIBgkOVPubX8syUcxwSmkw2OAfwiHu','admin4_pseudo',NULL,'ADMIN');
